spring.application.name=LoadBalancer
server.port=8080
spring.task.scheduling.pool.size=1
loadbalancer.servers=http://localhost:8081,http://localhost:8082,http://localhost:8083,http://localhost:8084
loadbalancer.algorithm=round-robin
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.security.enabled=false
management.endpoints.web.exposure.include=refresh
spring.cloud.config.import-check.enabled=false


